name: Teleese 24/7 Keep-Alive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-room:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        room_id: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: |
          npm install --no-audit --no-fund
          npx puppeteer install

      - name: Execute
        env:
          ROOM_ID: ${{ matrix.room_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAXBALL_TOKEN: ${{ secrets[format('TOKEN_{0}', matrix.room_id)] }}
        run: |
          # Solo la Sala 0 manda el relevo para evitar el bucle x8
          if [ "${{ matrix.room_id }}" == "0" ]; then
            (sleep 19200 && curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Test.yml/dispatches" \
              -d '{"ref":"main"}') &
            echo "ðŸš€ Relevo programado para las 5:20hs por Sala 0"
          fi

          # EjecuciÃ³n del bot con lÃ­mite de 6 horas
          timeout 21540s npm start || echo "Cambio de mando exitoso"
