name: Deploy 11 HaxBall Rooms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-room:
    runs-on: ubuntu-latest
    strategy:
      # Si una sala falla por token expirado, las otras 10 siguen funcionando
      fail-fast: false 
      matrix:
        # Esto crea los 11 procesos paralelos
        room_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: |
          npm install
          # Forzamos la instalación de los plugins de stealth por seguridad
          npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Instalar dependencias de Chrome (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev wget gnupg
          # Instalamos el binario de Chrome necesario para Puppeteer
          npx puppeteer install

      - name: Ejecutar Sala #${{ matrix.room_id }}
        env:
          ROOM_ID: ${{ matrix.room_id }}
          HAXBALL_TOKEN: ${{ secrets[format('TOKEN_{0}', matrix.room_id)] }}
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }} 
        run: |
          npm start
