name: Deploy Teleese Project Rooms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-room:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        room_id: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: |
          npm install
          npx puppeteer install

      - name: Ejecutar Sala 
        env:
          ROOM_ID: ${{ matrix.room_id }}
          
          # Lógica para activar Header o Footer basado en el ID
          IS_HEADER: ${{ matrix.room_id == 0 && 'true' || 'false' }}
          IS_FOOTER: ${{ matrix.room_id == 7 && 'true' || 'false' }}
          
          HAXBALL_TOKEN: ${{ secrets[format('TOKEN_{0}', matrix.room_id)] }}
          
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }} 
        run: |
          npm start
